/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedResultOfStationDto } from './pagedResultOfStationDto';

export interface ApiResponseOfPagedResultOfStationDto {
  isSuccess?: boolean;
  data?: PagedResultOfStationDto | null;
  message?: string | null;
}
