/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedResultOfVehicleDto } from './pagedResultOfVehicleDto';

export interface ApiResponseOfPagedResultOfVehicleDto {
  isSuccess?: boolean;
  data?: PagedResultOfVehicleDto | null;
  message?: string | null;
}
