/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RenterProfileDto2 } from './renterProfileDto2';

export interface ApiResponseOfListOfRenterProfileDto {
  isSuccess?: boolean;
  data?: Array<RenterProfileDto2> | null;
  message?: string | null;
}
