/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalDetailsDto2 } from './rentalDetailsDto2';

export interface ApiResponseOfListOfRentalDetailsDto {
  isSuccess?: boolean;
  data?: Array<RentalDetailsDto2> | null;
  message?: string | null;
}
