/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DepositFeeDto } from './depositFeeDto';

export interface ApiResponseOfDepositFeeDto {
  isSuccess?: boolean;
  data?: DepositFeeDto | null;
  message?: string | null;
}
