/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StationDetailsDto } from './stationDetailsDto';

export interface ApiResponseOfStationDetailsDto {
  isSuccess?: boolean;
  data?: StationDetailsDto | null;
  message?: string | null;
}
