/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedResultOfRentalDto } from './pagedResultOfRentalDto';

export interface ApiResponseOfPagedResultOfRentalDto {
  isSuccess?: boolean;
  data?: PagedResultOfRentalDto | null;
  message?: string | null;
}
