/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedResultOfBookingDetailsDto } from './pagedResultOfBookingDetailsDto';

export interface ApiResponseOfPagedResultOfBookingDetailsDto {
  isSuccess?: boolean;
  data?: PagedResultOfBookingDetailsDto | null;
  message?: string | null;
}
