/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VnPayPaymentResponseDto } from './vnPayPaymentResponseDto';

export interface ApiResponseOfVnPayPaymentResponseDto {
  isSuccess?: boolean;
  data?: VnPayPaymentResponseDto | null;
  message?: string | null;
}
