/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VnPayRefundResponseDto } from './vnPayRefundResponseDto';

export interface ApiResponseOfVnPayRefundResponseDto {
  isSuccess?: boolean;
  data?: VnPayRefundResponseDto | null;
  message?: string | null;
}
