/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractDetailsDto } from './contractDetailsDto';

export interface ApiResponseOfContractDetailsDto {
  isSuccess?: boolean;
  data?: ContractDetailsDto | null;
  message?: string | null;
}
