/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BookingDetailsDto {
  bookingId?: string;
  renterId?: string;
  vehicleAtStationId?: string;
  bookingCreatedAt?: string;
  startTime?: string;
  endTime?: string;
  status?: number;
  verificationStatus?: number;
  verifiedByStaffId?: string | null;
  verifiedAt?: string | null;
  cancelReason?: string | null;
}
