/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: pending, approved, rejected_Mismatch, rejected_Other.
 */
export const BookingVerificationStatus = {
  Pending: 'pending',
  Approved: 'approved',
  RejectedMismatch: 'rejected_Mismatch',
  RejectedOther: 'rejected_Other',
} as const;
export type BookingVerificationStatus =
  (typeof BookingVerificationStatus)[keyof typeof BookingVerificationStatus];
