/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Pending_Verification, Verified, Cancelled.
 */
export const BookingStatus = {
  PendingVerification: 'Pending_Verification',
  Verified: 'Verified',
  Cancelled: 'Cancelled',
} as const;
export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];
