/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingDetailsDtoPagedResult } from './bookingDetailsDtoPagedResult';

export interface BookingDetailsDtoPagedResultApiResponse {
  isSuccess?: boolean;
  data?: BookingDetailsDtoPagedResult;
  message?: string | null;
}
