/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingVerificationStatus } from './bookingVerificationStatus';
import { BookingStatus } from './bookingStatus';

export interface BookingDetailsDto {
  bookingId?: string;
  renterId?: string;
  vehicleAtStationId?: string;
  bookingCreatedAt?: string;
  startTime?: string;
  endTime?: string;
  status?: BookingStatus;
  verificationStatus?: BookingVerificationStatus;
  verifiedByStaffId?: string | null;
  verifiedAt?: string | null;
  cancelReason?: string | null;
}
export namespace BookingDetailsDto {}
