/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Pending, Approved, Rejected_Mismatch, Rejected_Other.
 */
export const BookingVerificationStatus = {
  Pending: 'Pending',
  Approved: 'Approved',
  RejectedMismatch: 'Rejected_Mismatch',
  RejectedOther: 'Rejected_Other',
} as const;
export type BookingVerificationStatus =
  (typeof BookingVerificationStatus)[keyof typeof BookingVerificationStatus];
