/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RenterBankAccountDto } from './renterBankAccountDto';

export interface CancelCheckinRequest {
  bookingId?: string;
  cancelReason?: string;
  cancelCheckinCode?: string;
  renterBankAccount?: RenterBankAccountDto | null;
}
