/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingVerificationStatus } from './bookingVerificationStatus';

export interface CheckinBookingRequest {
  bookingId?: string;
  verifiedByStaffId?: string;
  bookingVerificationStatus?: BookingVerificationStatus;
  cancelReason?: string | null;
}
export namespace CheckinBookingRequest {}
