/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Issued, Partially_Signed, Signed, Voided, Expired.
 */
export const ContractStatus = {
  Issued: 'Issued',
  PartiallySigned: 'Partially_Signed',
  Signed: 'Signed',
  Voided: 'Voided',
  Expired: 'Expired',
} as const;
export type ContractStatus = (typeof ContractStatus)[keyof typeof ContractStatus];
