/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ContractDetailsDto {
  contractId?: string;
  rentalId?: string;
  status?: number;
  issuedAt?: string;
  completedAt?: string | null;
  provider?: number;
  providerEnvelopeId?: string | null;
  documentUrl?: string;
  documentHash?: string;
  auditTrailUrl?: string | null;
  updatedAt?: string;
}
