/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: issued, partially_Signed, signed, voided, expired.
 */
export const ContractStatus = {
  Issued: 'issued',
  PartiallySigned: 'partially_Signed',
  Signed: 'signed',
  Voided: 'voided',
  Expired: 'expired',
} as const;
export type ContractStatus = (typeof ContractStatus)[keyof typeof ContractStatus];
