/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractStatus } from './contractStatus';
import { EsignProvider } from './esignProvider';

export interface ContractDetailsDto {
  contractId?: string;
  rentalId?: string;
  status?: ContractStatus;
  issuedAt?: string;
  completedAt?: string | null;
  provider?: EsignProvider;
  providerEnvelopeId?: string | null;
  documentUrl?: string | null;
  documentHash?: string | null;
  auditTrailUrl?: string | null;
  updatedAt?: string;
}
export namespace ContractDetailsDto {}
