/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateBookingRequest {
  renterId?: string;
  vehicleAtStationId?: string;
  startTime?: string;
  endTime?: string;
  depositDescription?: string;
  depositAmount?: number;
  depositCurrency?: number;
  paymentMethod?: number;
  amountPaid?: number;
  paidAt?: string;
  providerReference?: string | null;
}
