/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateSignaturePayloadDto {
  contractId?: string;
  documentUrl?: string;
  documentHash?: string;
  role?: number;
  signatureEvent?: number;
  type?: number;
  signedAt?: string;
}
