/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EsignProvider } from './esignProvider';

export interface CreateContractRequest {
  rentalId?: string;
  provider?: EsignProvider;
}
export namespace CreateContractRequest {}
