/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartyRole } from './partyRole';
import { SignatureEvent } from './signatureEvent';
import { SignatureType } from './signatureType';

export interface CreateSignaturePayloadDto {
  contractId?: string;
  documentUrl?: string | null;
  documentHash?: string | null;
  role?: PartyRole;
  signatureEvent?: SignatureEvent;
  type?: SignatureType;
  signedAt?: string;
}
export namespace CreateSignaturePayloadDto {}
