/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: USD, VND.
 */
export const Currency = {
  Usd: 'USD',
  Vnd: 'VND',
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];
