/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeeType } from './feeType';
import { Currency } from './currency';
import { PaymentMethod } from './paymentMethod';

export interface DepositFeeDto {
  type?: FeeType;
  description?: string | null;
  amount?: number;
  currency?: Currency;
  method?: PaymentMethod;
  amountPaid?: number;
  createdAt?: string;
  providerReference?: string | null;
}
export namespace DepositFeeDto {}
