/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DepositFeeDto {
  type?: number;
  description?: string;
  amount?: number;
  currency?: number;
  method?: number;
  amountPaid?: number;
  paidAt?: string;
  createdAt?: string;
  providerReference?: string | null;
}
