/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';

export interface ErrorMessage {
  message?: string | null;
  errorDetails?: Array<ErrorDetail> | null;
}
