/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Native, Docusign, Adobesign, Signnow, Other.
 */
export const EsignProvider = {
  Native: 'Native',
  Docusign: 'Docusign',
  Adobesign: 'Adobesign',
  Signnow: 'Signnow',
  Other: 'Other',
} as const;
export type EsignProvider = (typeof EsignProvider)[keyof typeof EsignProvider];
