/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: native, docusign, adobesign, signnow, other.
 */
export const EsignProvider = {
  Native: 'native',
  Docusign: 'docusign',
  Adobesign: 'adobesign',
  Signnow: 'signnow',
  Other: 'other',
} as const;
export type EsignProvider = (typeof EsignProvider)[keyof typeof EsignProvider];
