/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ESignPayloadDto {
  signerIp?: string | null;
  userAgent?: string | null;
  providerSignatureId?: string | null;
  signatureImageUrl?: string | null;
  certSubject?: string | null;
  certIssuer?: string | null;
  certSerial?: string | null;
  certFingerprintSha256?: string | null;
  signatureHash?: string | null;
  evidenceUrl?: string | null;
}
