/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: deposit, rental_Charge, surcharge, damage, other.
 */
export const FeeType = {
  Deposit: 'deposit',
  RentalCharge: 'rental_Charge',
  Surcharge: 'surcharge',
  Damage: 'damage',
  Other: 'other',
} as const;
export type FeeType = (typeof FeeType)[keyof typeof FeeType];
