/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Deposit, Rental_Charge, Surcharge, Damage, Other.
 */
export const FeeType = {
  Deposit: 'Deposit',
  RentalCharge: 'Rental_Charge',
  Surcharge: 'Surcharge',
  Damage: 'Damage',
  Other: 'Other',
} as const;
export type FeeType = (typeof FeeType)[keyof typeof FeeType];
