/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: national_ID, driver_License, passport, other.
 */
export const KycType = {
  NationalId: 'national_ID',
  DriverLicense: 'driver_License',
  Passport: 'passport',
  Other: 'other',
} as const;
export type KycType = (typeof KycType)[keyof typeof KycType];
