/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: National_ID, Driver_License, Passport, Other.
 */
export const KycType = {
  NationalId: 'National_ID',
  DriverLicense: 'Driver_License',
  Passport: 'Passport',
  Other: 'Other',
} as const;
export type KycType = (typeof KycType)[keyof typeof KycType];
