/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingDetailsDto } from './bookingDetailsDto';

export interface PagedResultOfBookingDetailsDto {
  items: Array<BookingDetailsDto>;
  total: number;
  page: number;
  pageSize: number;
}
