/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalDto } from './rentalDto';

export interface PagedResultOfRentalDto {
  items: Array<RentalDto>;
  total: number;
  page: number;
  pageSize: number;
}
