/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Renter, Staff, Other.
 */
export const PartyRole = {
  Renter: 'Renter',
  Staff: 'Staff',
  Other: 'Other',
} as const;
export type PartyRole = (typeof PartyRole)[keyof typeof PartyRole];
