/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: renter, staff, other.
 */
export const PartyRole = {
  Renter: 'renter',
  Staff: 'staff',
  Other: 'other',
} as const;
export type PartyRole = (typeof PartyRole)[keyof typeof PartyRole];
