/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: unknown, cash, card, ewallet, bank_Transfer, vnPay_QR, international_Card.
 */
export const PaymentMethod = {
  Unknown: 'unknown',
  Cash: 'cash',
  Card: 'card',
  Ewallet: 'ewallet',
  BankTransfer: 'bank_Transfer',
  VnPayQr: 'vnPay_QR',
  InternationalCard: 'international_Card',
} as const;
export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];
