/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Unknown, Cash, Card, Ewallet, Bank_Transfer, VNPay_QR, International_Card.
 */
export const PaymentMethod = {
  Unknown: 'Unknown',
  Cash: 'Cash',
  Card: 'Card',
  Ewallet: 'Ewallet',
  BankTransfer: 'Bank_Transfer',
  VnPayQr: 'VNPay_QR',
  InternationalCard: 'International_Card',
} as const;
export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];
