/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RenterProfileDto {
  renterId?: string;
  driverLicenseNo?: string | null;
  dateOfBirth?: string | null;
  address?: string | null;
  riskScore?: number;
}
