/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingBriefDto } from './bookingBriefDto';
import { ContractDto } from './contractDto';
import { VehicleDto } from './vehicleDto';
import { RentalStatus } from './rentalStatus';

export interface RentalDetailsDto {
  rentalId?: string;
  bookingId?: string;
  vehicleId?: string;
  startTime?: string;
  endTime?: string;
  status?: RentalStatus;
  score?: number;
  comment?: string | null;
  ratedAt?: string;
  booking?: BookingBriefDto;
  vehicle?: VehicleDto;
  contracts?: Array<ContractDto> | null;
}
export namespace RentalDetailsDto {}
