/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalDetailsDto } from './rentalDetailsDto';

export interface RentalDetailsDtoApiResponse {
  isSuccess?: boolean;
  data?: RentalDetailsDto;
  message?: string | null;
}
