/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalDtoPagedResult } from './rentalDtoPagedResult';

export interface RentalDtoPagedResultApiResponse {
  isSuccess?: boolean;
  data?: RentalDtoPagedResult;
  message?: string | null;
}
