/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RenterProfileDto } from './renterProfileDto';

export interface RenterProfileDtoListApiResponse {
  isSuccess?: boolean;
  data?: Array<RenterProfileDto> | null;
  message?: string | null;
}
