/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Reserved, In_Progress, Completed, Late, Cancelled.
 */
export const RentalStatus = {
  Reserved: 'Reserved',
  InProgress: 'In_Progress',
  Completed: 'Completed',
  Late: 'Late',
  Cancelled: 'Cancelled',
} as const;
export type RentalStatus = (typeof RentalStatus)[keyof typeof RentalStatus];
