/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalStatus } from './rentalStatus';

export interface RentalDto {
  rentalId?: string;
  bookingId?: string;
  vehicleId?: string;
  startTime?: string;
  endTime?: string;
  status?: RentalStatus;
  score?: number;
  comment?: string | null;
  ratedAt?: string;
}
export namespace RentalDto {}
