/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: reserved, in_Progress, completed, late, cancelled.
 */
export const RentalStatus = {
  Reserved: 'reserved',
  InProgress: 'in_Progress',
  Completed: 'completed',
  Late: 'late',
  Cancelled: 'cancelled',
} as const;
export type RentalStatus = (typeof RentalStatus)[keyof typeof RentalStatus];
