/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: drawn, typed, digital_Cert, onPaper.
 */
export const SignatureType = {
  Drawn: 'drawn',
  Typed: 'typed',
  DigitalCert: 'digital_Cert',
  OnPaper: 'onPaper',
} as const;
export type SignatureType = (typeof SignatureType)[keyof typeof SignatureType];
