/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Pickup, Dropoff.
 */
export const SignatureEvent = {
  Pickup: 'Pickup',
  Dropoff: 'Dropoff',
} as const;
export type SignatureEvent = (typeof SignatureEvent)[keyof typeof SignatureEvent];
