/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSignaturePayloadDto } from './createSignaturePayloadDto';
import { ESignPayloadDto } from './eSignPayloadDto';

export interface SignContractRequest {
  createSignaturePayloadDto?: CreateSignaturePayloadDto;
  eSignPayload?: ESignPayloadDto;
}
