/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Drawn, Typed, Digital_Cert, OnPaper.
 */
export const SignatureType = {
  Drawn: 'Drawn',
  Typed: 'Typed',
  DigitalCert: 'Digital_Cert',
  OnPaper: 'OnPaper',
} as const;
export type SignatureType = (typeof SignatureType)[keyof typeof SignatureType];
