/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDto } from './vehicleDto';

export interface StationDetailsDto {
  id?: string;
  name?: string | null;
  address?: string | null;
  capacity?: number;
  vehicles?: Array<VehicleDto> | null;
}
