/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StationDto } from './stationDto';

export interface StationDtoPagedResult {
  items?: Array<StationDto> | null;
  total?: number;
  page?: number;
  pageSize?: number;
}
