/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KycType } from './kycType';

export interface UploadKycRequest {
  type?: KycType;
  documentNumber?: string | null;
}
export namespace UploadKycRequest {}
