/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './userInfoDto';

export interface UserInfoDtoApiResponse {
  isSuccess?: boolean;
  data?: UserInfoDto;
  message?: string | null;
}
