/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingBriefDto } from './bookingBriefDto';
import { VehicleAtStationStatus } from './vehicleAtStationStatus';

export interface VehicleDetailsDto {
  vehicleId?: string;
  make?: string | null;
  model?: string | null;
  modelYear?: number;
  rangeKm?: number;
  vehicleAtStationId?: string;
  currentBatteryCapacityKwh?: number;
  rentalPricePerHour?: number;
  rentalPricePerDay?: number | null;
  depositPrice?: number;
  status?: VehicleAtStationStatus;
  upcomingBookings?: Array<BookingBriefDto> | null;
}
export namespace VehicleDetailsDto {}
