/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: Maintenance, Available, Booked.
 */
export const VehicleAtStationStatus = {
  Maintenance: 'Maintenance',
  Available: 'Available',
  Booked: 'Booked',
} as const;
export type VehicleAtStationStatus =
  (typeof VehicleAtStationStatus)[keyof typeof VehicleAtStationStatus];
