/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDtoPagedResult } from './vehicleDtoPagedResult';

export interface VehicleDtoPagedResultApiResponse {
  isSuccess?: boolean;
  data?: VehicleDtoPagedResult;
  message?: string | null;
}
