/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDetailsDto } from './vehicleDetailsDto';

export interface VehicleDetailsDtoApiResponse {
  isSuccess?: boolean;
  data?: VehicleDetailsDto;
  message?: string | null;
}
