/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Possible values: maintenance, available, booked.
 */
export const VehicleAtStationStatus = {
  Maintenance: 'maintenance',
  Available: 'available',
  Booked: 'booked',
} as const;
export type VehicleAtStationStatus =
  (typeof VehicleAtStationStatus)[keyof typeof VehicleAtStationStatus];
