/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VehicleDto {
  vehicleAtStationId?: string;
  vehicleId?: string;
  stationId?: string;
  startTime?: string;
  endTime?: string | null;
  currentBatteryCapacityKwh?: number;
  status?: number;
}
