/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VnPayQueryResponseDto } from './vnPayQueryResponseDto';

export interface VnPayQueryResponseDtoApiResponse {
  isSuccess?: boolean;
  data?: VnPayQueryResponseDto;
  message?: string | null;
}
