/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayPaymentRequestDto {
  orderId?: string;
  amount?: number;
  orderDescription?: string;
  bankCode?: string | null;
  locale?: string;
  orderType?: string;
  ipAddress?: string;
}
