/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayQueryResponseDto {
  responseId?: string;
  command?: string;
  responseCode?: string;
  message?: string;
  txnRef?: string;
  amount?: number;
  bankCode?: string;
  payDate?: string;
  transactionNo?: string;
  transactionStatus?: string;
}
