/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayRefundRequestDto {
  orderId?: string | null;
  transactionDate?: string | null;
  amount?: number;
  transactionType?: string | null;
  transactionNo?: string | null;
  createdBy?: string | null;
  ipAddress?: string | null;
}
