/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayQueryRequestDto {
  orderId?: string | null;
  transactionDate?: string | null;
  ipAddress?: string | null;
}
