/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayReturnDto {
  orderId?: string;
  transactionId?: number;
  amount?: number;
  bankCode?: string;
  bankTranNo?: string;
  cardType?: string;
  responseCode?: string;
  transactionStatus?: string;
  payDate?: string;
  isSuccess?: boolean;
  isValidSignature?: boolean;
  orderInfo?: string;
}
