/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayQueryResponseDto {
  responseId?: string | null;
  command?: string | null;
  responseCode?: string | null;
  message?: string | null;
  txnRef?: string | null;
  amount?: number;
  bankCode?: string | null;
  payDate?: string | null;
  transactionNo?: string | null;
  transactionStatus?: string | null;
}
