/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VnPayReturnDto } from './vnPayReturnDto';

export interface VnPayReturnDtoApiResponse {
  isSuccess?: boolean;
  data?: VnPayReturnDto;
  message?: string | null;
}
