/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayReturnDto {
  orderId?: string | null;
  transactionId?: number;
  amount?: number;
  bankCode?: string | null;
  bankTranNo?: string | null;
  cardType?: string | null;
  responseCode?: string | null;
  transactionStatus?: string | null;
  payDate?: string;
  isSuccess?: boolean;
  isValidSignature?: boolean;
  orderInfo?: string | null;
}
