/**
 * EV Rental API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VnPayRefundRequestDto {
  orderId?: string;
  transactionDate?: string;
  amount?: number;
  transactionType?: string;
  transactionNo?: string | null;
  createdBy?: string;
  ipAddress?: string;
}
